# -*- coding: utf-8 -*-
"""frontend_streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_I-vQMusYZmC5DApEnA6mwkMRs4kcArD
"""

import streamlit as st
import pandas as pd
import pickle

# Load model
with open("random_forest_model.pkl", "rb") as f:
    model = pickle.load(f)

st.title("Prediksi Risiko Penyakit Terkait COVID-19")

st.markdown("Isi data di bawah untuk memprediksi tingkat risiko:")

# Sidebar Form Input
st.sidebar.header("Form Input Pengguna")

def user_input():
    Age = st.sidebar.slider("Umur", 0, 100, 30)
    Gender = st.sidebar.selectbox("Jenis Kelamin", ["Male", "Female"])
    Region = st.sidebar.selectbox("Wilayah", ["Urban", "Rural"])
    Occupation = st.sidebar.selectbox("Pekerjaan", ["Healthcare", "Non-Healthcare"])
    Symptoms = st.sidebar.selectbox("Mengalami Gejala?", ["Yes", "No"])
    Preexisting_Condition = st.sidebar.selectbox("Kondisi Penyakit Bawaan?", ["Yes", "No"])
    Smoking_Status = st.sidebar.selectbox("Status Merokok", ["Smoker", "Non-Smoker"])
    BMI = st.sidebar.slider("BMI", 10.0, 50.0, 22.0)
    Vaccination_Status = st.sidebar.selectbox("Status Vaksinasi", ["Vaccinated", "Not Vaccinated"])
    Doses_Received = st.sidebar.slider("Jumlah Dosis Vaksin", 0, 4, 2)
    Reinfection = st.sidebar.selectbox("Reinfeksi?", ["Yes", "No"])
    COVID_Strain = st.sidebar.selectbox("Strain COVID", ["Alpha", "Beta", "Delta", "Omicron"])
    ICU_Admission = st.sidebar.selectbox("Pernah Masuk ICU?", ["Yes", "No"])
    Ventilator_Support = st.sidebar.selectbox("Pernah Pakai Ventilator?", ["Yes", "No"])
    Recovered = st.sidebar.selectbox("Sudah Sembuh?", ["Yes", "No"])
    Severity = st.sidebar.selectbox("Tingkat Keparahan", ["Mild", "Moderate", "Severe"])

    # Gabungkan semua jadi dataframe
    data = {
        "Age": Age,
        "Gender": Gender,
        "Region": Region,
        "Occupation": Occupation,
        "Symptoms": Symptoms,
        "Preexisting_Condition": Preexisting_Condition,
        "Smoking_Status": Smoking_Status,
        "BMI": BMI,
        "Vaccination_Status": Vaccination_Status,
        "Doses_Received": Doses_Received,
        "Reinfection": Reinfection,
        "COVID_Strain": COVID_Strain,
        "ICU_Admission": ICU_Admission,
        "Ventilator_Support": Ventilator_Support,
        "Recovered": Recovered,
        "Severity": Severity,
    }

    return pd.DataFrame([data])

# Ambil input pengguna
input_df = user_input()

st.subheader("Data yang Diberikan")
st.write(input_df)

# Encode categorical features jika perlu (opsional: jika model pakai OneHot atau LabelEncoder)
# Pastikan model kamu tidak perlu preprocessing tambahan (sudah termasuk di pipeline)

# Prediksi
prediction = model.predict(input_df)
prediction_proba = model.predict_proba(input_df)

# Tampilkan hasil
st.subheader("Hasil Prediksi")
st.write(f"**Risiko Terkait COVID:** {'Tinggi' if prediction[0] == 1 else 'Rendah'}")
st.write(f"**Probabilitas:** Rendah: {prediction_proba[0][0]:.2f} | Tinggi: {prediction_proba[0][1]:.2f}")

!pip install streamlit